install_data(
  'xyz.xaminezh.TvWeb.desktop',
  install_dir: get_option('datadir') / 'applications',
)

install_data(
  'xyz.xaminezh.TvWeb.metainfo.xml',
  install_dir: get_option('datadir') / 'metainfo',
)

install_data(
  'icons/hicolor/scalable/apps/xyz.xaminezh.TvWeb.svg',
  install_dir: get_option('datadir') / 'icons' / 'hicolor' / 'scalable' / 'apps',
)
